### PR TITLE
API design draft

### PR DESCRIPTION
**Pull request by tsimbalar**
Here is a first *design* of what I believe the whole **Combined** thing could look like ....

At the core of it is `Serilog.Settings.Combined.ISettingsSource` that looks like this : 

```csharp
public interface ISettingsSource
{
    IReadOnlyDictionary<string, string> GetSettings(IReadOnlyDictionary<string, string> alreadyDefinedSettings);
}
```

Implementers can implement `ISettingsSource` to add settings from somewhere, but possibly also remove or alter settings ... 
The interface exposes only `IReadOnlyDictionary` to make it clear that :
- settings keys are expected to be unique
- you're not suppose to touch the settings you are provided, but instead return copies

The idea is to combine multiple instances of `ISettingSource` into a **pipeline**, with one source feeding on the output of the previous pipeline ... 

In order to *build* that pipeline, one can use :
- `ReadFrom.Combined(params ISettingsSource[] sources)` to combine already existing sources
- `ReadFrom.Combined(Func<ISettingsSourcePipelineBuilder, ISettingsSourcePipelineBuilder> combine)` to build it in a more fluent way

`ISettingsSourcePipelineBuilder` looks like this : 

```csharp
public interface ISettingsSourcePipelineBuilder
{
    ISettingsSourcePipelineBuilder AddSource(ISettingsSource settingSource);
}
```

Implementers can provide extension methods for `ISettingsSourcePipelineBuilder` to plug their custom `ISettingsSource` in the pipeline.

Out of the box, we can provide simple extensions like `AddKeyValuePair()`, `AddKeyValuePairs` etc ... that allows to write the configuration like this ;

```csharp
var log = new LoggerConfiguration()
    .ReadFrom.Combined(builder => builder
        .AddKeyValuePairs(new Dictionary<string, string>
        {
            {"enrich:with-property:UntouchedProp", "initialValue"},
            {"enrich:with-property:OverridenProp", "initialValue"},
        })
        .AddKeyValuePair("enrich:with-property:OverridenProp", "changedValue")
        .AddKeyValuePair("enrich:with-property:NewProp", "value")
        .AddKeyValuePair(new KeyValuePair<string, string>("enrich:with-property:OverridenProp", "overridenValue"))
        )
    .WriteTo.Sink(new DelegatingSink(e => evt = e))
    .CreateLogger();
```

@serilog/reviewers-core any opinion on the topic ? :) 

Now I'll be off on a vacation for a week  🚗

### CODE REVIEW

**Comment by nblumhardt** [comment]
Hope you're having a good vacation! 🌴 🏄 🌞

First impressions, just taking a look at it from the high-level perspective.

If `AddKeyValuePairs()` was directly implemented on `CombinedSettingsBuilder` then `AddEnvironmentVariables()`, `AddAppSettings()` and so on would just be thin wrappers over it. This would reduce the number of moving parts - we wouldn't need an `ISettingsSource`, and the builder would just be a way to create a `Dictionary<string, string>` that `Combined()` would pass through to `LoggerSettingsConfiguration.KeyValuePairs()`.

E.g.:

```csharp
var builder = new CombinedSettingsBuilder();
configure(builder); // calls Add*()
var pairs = builder.BuildSettings();
return loggerSettingsConfiguration.KeyValuePairs(pairs);
```

`builder.BuildSettings()` would be a nice helper for testing the various `Add*()` extensions, too.

Unrelated, the current Serilog `ReadFrom.KeyValuePairs()` method accepts `IEnumerable<KeyValuePair<string, string>>` and (should) apply precedence rules to enforce a last-in-wins system of overrides. Could we avoid making decisions about how to handle duplicate keys here in _combined_, and instead just base this around `IEnumerable<KeyValuePair<string, string>>` too? This way, the builder would end up concatenating all of the settings from the various providers, and pass this through to have the default `KeyValuePairs()` method figure out what to do with any duplicates. The benefit would be a consistent model for collections of settings (since the other API already exists and is unlikely to change).

**Comment by tsimbalar** [comment]
Back from holidays 🌞 

Yes, I guess I got a bit carried away and fell in the *YAGNI* trap (again!). I guess I was just trying to cover too much stuff in it. 

I'll simplify it according to your comments :)

> Unrelated, the current Serilog ReadFrom.KeyValuePairs() method accepts IEnumerable<KeyValuePair<string, string>> and (should) apply precedence rules to enforce a last-in-wins system of overrides. Could we avoid making decisions about how to handle duplicate keys here in combined, and instead just base this around IEnumerable<KeyValuePair<string, string>> too? 

That makes sense :)
I have updated my pull request serilog/serilog#1051 to add this behavior. I'll wait for it to be merged in dev so that I can rely on a pre-release version of Serilog v2.6.0 in here.

**Comment by nblumhardt** [comment]
I think I'm going to struggle for time to provide a meaningful review of this right now; perhaps merging this and tinkering with it "in action" for a while might be a better way to propel it forwards? Happy to hit the button if you're okay with that plan.

**Comment by tsimbalar** [comment]
Sure .... Maybe I would go ahead and release a *non-prerelease* v0.1 .... at least to start trying to integrate it in *Serilog.Settings.AppSettings* and *Serilog.Settings.Configuration* .

**Comment by nblumhardt** [comment]
Howdy! I don't know if there's such thing as a non-prerelease 0.x build in the SemVer scheme.

I was going on the assumption we'd duplicate any code needed from _Serilog.Settings.AppSettings_ etc. over here to get the ball rolling - adding inter-package dependencies makes iterating hard. If/when we arrive at something we're happy with here, it'd be a candidate for going in the _Serilog_ package itself in v3 (or at least the hook to enable it would). Does that sound viable?

**Comment by tsimbalar** [comment]
oh, ok, I hadn't thought of it that way, but that sounds good :)

**Pull request merged**
